title: Anderson Reyes
description: I'm a senior at Rutgers University(Grad May 2018). I work as a research assistant at CoDas Lab (link below). I'm interested in AI, Machine/Deep/Reinforcement Learning. As a hobby I like learning about systems programming like compilers/interpreters, operating systems, and other low level coding stuff.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
